# Generated by Django 3.0.4 on 2020-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20201230_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
