# Generated by Django 3.0.4 on 2021-01-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20201230_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='thumb',
        ),
    ]
