# Generated by Django 3.0.4 on 2021-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('number', models.SmallIntegerField()),
                ('typeOfMeasure', models.CharField(choices=[('ct', 'Count'), ('gal', 'Gallon'), ('lb', 'Pound'), ('liter', 'Liter'), ('box', 'Box'), ('doz', 'Dozen'), ('case', 'Case')], default='ct', max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
