# Generated by Django 3.0.4 on 2021-01-14 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donationDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='donation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donations.Donation'),
            preserve_default=False,
        ),
    ]
