# Generated by Django 3.0.4 on 2021-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20210114_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='locationName',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
