# Generated by Django 3.0.4 on 2021-04-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='Questionnaire',
        ),
    ]
